- name: Create an EC2 Instance
  ec2:
    region: "{{ ec2.region }}"
    keypair: "{{ ec2.credentials }}"
    instance_tags: "{{ ec2.tags }}"
    image: "{{ ec2.image }}"
    instance_type: "{{ ec2.instance_type }}"
    instance_profile_name: "{{ ec2.role | default('') }}"
    group: "{{ ec2.sg }}"
    vpc_subnet_id: "{{ ec2.subnet }}"
    assign_public_ip: "{{ ec2.public_ip | default('no') }}"
    private_ip: "{{ ec2.private_ip | default('') }}"
    wait: true